### ISSUE TITLE
Installation (suggestions)

### ISSUE THREAD

**Issue by iferres** [BackofenLab/Casboundary#2]
Some recommendations. I'm trying to install Casboundary into a Singularity container and I'm finding some difficulties.

See the singularity file (very similar to a docker file in structure)
```
Bootstrap: docker
From: mambaorg/micromamba:1.4.9

%files
        ./v1.0.1.zip /opt/                  # Copy latest version from current dir into the container
        ./*.tar /opt/                       # Copy the four '.tar' files from current dir into the container

%post
        apt update -y && apt install zip  -y
        unzip /opt/v1.0.1.zip -d /opt/                            # Unzip Casboundary
        mv /opt/*.tar /opt/Casboundary-1.0.1/                     # Move models into installation path
        cd /opt/Casboundary-1.0.1/                                # Go inside installation path
        chmod +x *.py                                             # Make all py files executable
        tar -xf Cas_HMM.tar                                       # Untar models ...
        tar -xf Gen_HMM.tar
        tar -xf ML_models.tar
        tar -xf Cas_HMM.tar
        micromamba create -f casboundary-env.yml       # Create and solve env
        micromamba clean --all --yes

%environment
        export PATH=/opt/Casboundary-1.0.1:/opt/conda/envs/casboundary-env/bin:$PATH  # Export binary paths to PATH 

%runscript
         python /opt/Casboundary-1.0.1/Casboundary.py "$@"  # Runscript
```
The models are compressed as `.tar` files, but the script tries to find `.tar.gz` files: 
https://github.com/BackofenLab/Casboundary/blob/eea3c99c777b60cfe3a2e6a9d47f8e1314e7d5d0/Casboundary.py#L48 

And also, when I call `Casboundaries.py` from any other path, it fails because none of the directories are located in the working directory. It seems one only can run it from the installation directory where the models are located. 
```
$ singularity run /home/iferres/singularity/casboundary/casboundary.sif -f dummy.fasta -c complete
Traceback (most recent call last):
  File "/opt/Casboundary-1.0.1/Casboundary.py", line 311, in <module>
    extract_targz(CAS_HMM_TAR_PATH)
  File "/opt/Casboundary-1.0.1/utils.py", line 31, in extract_targz
    raise ValueError(f'{targz_file_path} file not found. You should download it from our Google Drive. See README.md for details.')
ValueError: Cas_HMM.tar.gz file not found. You should download it from our Google Drive. See README.md for details.
```
Maybe an option to point to a location where all the models are located would solve this issue. Something like:
```
Casboundary.py ... --models_dir /path/to/models/ dummy.fasta
```
Also note that `Casboundary.py` doesn't have a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)), and so you need to specify `python /path/to/Casboundary.py`. Putting something like `#!/usr/bin/env python` at the beginning of the script would allow to call it directly, like `./Casboundary`, without need to call the python interpreter.

Thank you for this cool pipeline, by the way.

**Comment by iferres** [comment]
Ignore the `.tar` vs `.tar.gz`, my system was automatically gunzipping the files. Sorry 😅
